"""
PDF Export Service — generate PDF from Commander sessions / research reports

Uses: reportlab (pure Python, no system deps) — install with: pip install reportlab
Falls back to printable HTML if reportlab not available.
"""
import os, io, json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

OUTPUT_DIR = Path(__file__).parent.parent.parent / "output" / "pdf"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    from reportlab.lib import colors
    REPORTLAB_OK = True
except ImportError:
    REPORTLAB_OK = False

try:
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    # Try to register a CJK font for Chinese support
    _cjk_font_registered = False
    for path in [
        r"C:\Windows\Fonts\msyh.ttc",  # Microsoft YaHei
        r"C:\Windows\Fonts\simsun.ttc",  # SimSun
        "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
        "/System/Library/Fonts/PingFang.ttc",
    ]:
        if os.path.exists(path):
            try:
                pdfmetrics.registerFont(TTFont('CJK', path))
                _cjk_font_registered = True
                break
            except Exception:
                continue
    CJK_FONT = 'CJK' if _cjk_font_registered else 'Helvetica'
except Exception:
    CJK_FONT = 'Helvetica'


def _html_body(title: str, content: str, extra: str = "") -> str:
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>{title}</title>
<style>@page {{ size: A4; margin: 20mm; }} body {{ font-family: system-ui; line-height: 1.8; color: #222; max-width: 700px; margin: auto; padding: 20px; }}
h1 {{ border-bottom: 2px solid #333; padding-bottom: 8px; }} h2 {{ margin-top: 24px; }}
pre {{ background: #f5f5f5; padding: 12px; border-radius: 4px; font-size: 12px; overflow-x: auto; }}
.footer {{ margin-top: 40px; padding-top: 10px; border-top: 1px solid #ccc; font-size: 11px; color: #888; }}
@media print {{ body {{ padding: 0; }} }}
</style></head><body>
<h1>{title}</h1>
{content}
{extra}
<div class="footer">Generated by AI Company OS v1.2.0 — {datetime.now().strftime('%Y-%m-%d %H:%M')}</div>
</body></html>"""


def export_session_pdf(session: dict, steps: List[dict], format: str = "pdf") -> str:
    """Export Commander session as PDF. Returns file path."""
    title = session.get("goal", "Commander Report")[:80]
    summary = session.get("summary", "") or ""

    content = f"<h2>Status: {session.get('status','?')}</h2>\n"
    content += f"<p>Steps: {session.get('completed_steps',0)}/{session.get('total_steps',0)} completed</p>\n"
    if summary:
        content += f"<h2>Summary</h2>\n<pre>{summary[:2000]}</pre>\n"

    content += "<h2>Execution Steps</h2>\n"
    for i, step in enumerate(steps, 1):
        agent = step.get("assigned_agent", "?")
        desc = step.get("description", "")[:100]
        status = step.get("status", "?")
        result = (step.get("result_summary", "") or "")[:200]
        content += f"<h3>Step {i}: {agent}</h3>\n"
        content += f"<p>{desc}</p>\n<p><b>Status:</b> {status}</p>\n"
        if result:
            content += f"<pre>{result}</pre>\n"

    extra = ""
    if steps:
        # Add a simple summary table
        extra = "<h2>Step Summary</h2><table border='1' cellpadding='4' cellspacing='0'><tr><th>Step</th><th>Agent</th><th>Status</th></tr>"
        for i, s in enumerate(steps, 1):
            extra += f"<tr><td>{i}</td><td>{s.get('assigned_agent','?')}</td><td>{s.get('status','?')}</td></tr>"
        extra += "</table>"

    html = _html_body(title, content, extra)
    filename = f"report_{session.get('session_id','unknown')}.html"
    filepath = OUTPUT_DIR / filename

    if format == "pdf" and REPORTLAB_OK:
        # Use reportlab for proper PDF
        pdf_path = str(filepath).replace('.html', '.pdf')
        doc = SimpleDocTemplate(pdf_path, pagesize=A4)
        styles = getSampleStyleSheet()
        story = [Paragraph(title, styles['Title']), Spacer(1, 12)]
        story.append(Paragraph(content.replace('<h2>','<b>').replace('</h2>','</b><br/>'), styles['Normal']))
        doc.build(story)
        return pdf_path

    filepath.write_text(html, encoding="utf-8")
    return str(filepath)


def export_markdown_report(title: str, body: str, format: str = "html") -> str:
    """Export markdown content as HTML/PDF"""
    html_content = body.replace("\n", "<br>\n") if "\n" in body else body
    html = _html_body(title, f"<pre>{html_content}</pre>" if "\n" in body else f"<p>{body}</p>")
    filename = f"report_{title[:30].replace(' ','_')}.html"
    filepath = OUTPUT_DIR / filename
    filepath.write_text(html, encoding="utf-8")
    return str(filepath)
