"""Generate the repository architecture inventory from source files."""
from __future__ import annotations

import argparse
import ast
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def _literal_string(node: ast.AST | None) -> str:
    if node is None:
        return ""
    try:
        value = ast.literal_eval(node)
    except (ValueError, TypeError, SyntaxError):
        return ""
    return value if isinstance(value, str) else ""


def _router_inventory() -> list[tuple[str, str, str]]:
    routes = [("/health", "GET", "backend/core_app.py")]
    for path in sorted((ROOT / "backend" / "routers").glob("*.py")):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except (OSError, SyntaxError):
            continue
        prefix = ""
        for node in ast.walk(tree):
            if not isinstance(node, ast.Assign):
                continue
            if isinstance(node.value, ast.Call) and isinstance(node.value.func, ast.Name) and node.value.func.id == "APIRouter":
                for keyword in node.value.keywords:
                    if keyword.arg == "prefix":
                        prefix = _literal_string(keyword.value)
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for decorator in node.decorator_list:
                if not isinstance(decorator, ast.Call) or not isinstance(decorator.func, ast.Attribute):
                    continue
                if decorator.func.attr not in {"get", "post", "put", "patch", "delete"}:
                    continue
                route = _literal_string(decorator.args[0] if decorator.args else None)
                if route:
                    full_path = (prefix.rstrip("/") + "/" + route.lstrip("/")).replace("//", "/") or "/"
                    routes.append((full_path, decorator.func.attr.upper(), path.relative_to(ROOT).as_posix()))
    return sorted(set(routes))


def _agent_inventory() -> list[str]:
    return sorted(
        path.relative_to(ROOT).as_posix()
        for path in (ROOT / "agents").glob("*/agent.py")
    )


def _dependency_inventory() -> list[str]:
    dependencies = []
    for path in sorted(ROOT.glob("requirements*.txt")):
        for line in path.read_text(encoding="utf-8").splitlines():
            item = line.strip()
            if item and not item.startswith("#"):
                dependencies.append((path.name, item))
    return sorted(set(dependencies))


def render() -> str:
    lines = [
        "# AI Company OS Architecture",
        "",
        "> Generated from the current source tree. Do not edit this file manually.",
        "",
        "## Runtime entrypoint",
        "",
        "- `backend/app.py` exposes the supported application.",
        "- `backend/core_app.py` assembles the Core FastAPI runtime.",
        "- `AIRegistry.scan_runtime_capabilities()` is the canonical capability snapshot entrypoint.",
        "",
        "## Routers",
        "",
        "| Method | Path | Source |",
        "|---|---|---|",
    ]
    lines.extend(f"| `{method}` | `{route}` | `{source}` |" for route, method, source in _router_inventory())
    lines.extend(["", "## Agents", "", "| Agent entrypoint |", "|---|"])
    lines.extend(f"| `{agent}` |" for agent in _agent_inventory())
    lines.extend(["", "## Python dependencies", "", "| Requirements file | Dependency |", "|---|---|"])
    lines.extend(f"| `{filename}` | `{dependency}` |" for filename, dependency in _dependency_inventory())
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "ARCHITECTURE.md")
    parser.add_argument("--check", action="store_true", help="fail when output differs from generated content")
    args = parser.parse_args()
    expected = render()
    output = args.output.resolve()
    if args.check:
        try:
            actual = output.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"architecture document missing: {exc}")
            return 1
        if actual != expected:
            print(f"architecture document is out of date: {output}")
            return 1
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
